### PR TITLE
i2c: validate the uniqueness of adapter with 'bus-name'

### PR DESCRIPTION
**Pull request by Q-LiuWei**
When the user selects 'bus-name' as device parameter, we need to ensure that there is only one adapter with that name. If not, the user should be notified.

### Summary of the PR

Make sure there is only one adapter with that name, otherwise the user won't know exactly which adapter is being opened.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x ] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x ] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x ] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Review by vireshk — DISMISSED** [review]

**Comment by Q-LiuWei** [comment]
s validata/validate in commit message

**Comment by vireshk** [comment]
> s validata/validate in commit message in the latest change

Please fix it and push it again.

**Comment by Q-LiuWei** [comment]
> > s validata/validate in commit message in the latest change
> 
> Please fix it and push it again.

Done.

**Comment by stefano-garzarella** [comment]
Do we really need to count how many devices share the same name?

I'd suggest simplifying the code in this way:

```patch
diff --git a/vhost-device-i2c/src/i2c.rs b/vhost-device-i2c/src/i2c.rs
index b5abb6a..7d94af3 100644
--- a/vhost-device-i2c/src/i2c.rs
+++ b/vhost-device-i2c/src/i2c.rs
@@ -48,8 +48,8 @@ pub(crate) enum Error {
     ClientAddressInvalid,
     #[error("Adapter not found")]
     AdapterNotFound,
-    #[error("{0} adapters share same name")]
-    AdapterShareSameName(u32),
+    #[error("Multiple adapters share the same name")]
+    AdapterShareSameName,
     #[error("Std IO Error")]
     StdIoErr,
     #[error("Failed while parsing to integer")]
@@ -350,8 +350,8 @@ impl PhysDevice {
     }
 
     fn find_adapter(name: &str) -> Result<u32> {
-        let mut adapter_no = 0;
-        let mut adapter_cnt: u32 = 0;
+        let mut adapter_no = None;
+
         for entry in
             fs::read_dir(Path::new("/sys/bus/i2c/devices/")).map_err(|_| Error::StdIoErr)?
         {
@@ -361,17 +361,20 @@ impl PhysDevice {
             let adapter_name = fs::read_to_string(path).map_err(|_| Error::StdIoErr)?;
 
             if adapter_name.trim() == name {
+                if adapter_no.is_some() {
+                    return Err(Error::AdapterShareSameName);
+                }
+
                 let path = entry.path();
                 let list: Vec<&str> = path.to_str().unwrap().split('-').collect();
-                adapter_no = list[1].parse::<u32>().map_err(|_| Error::ParseFailure)?;
-                adapter_cnt += 1;
+                adapter_no = Some(list[1].parse::<u32>().map_err(|_| Error::ParseFailure)?);
             }
         }
 
-        match adapter_cnt {
-            0 => Err(Error::AdapterNotFound),
-            1 => Ok(adapter_no),
-            _ => Err(Error::AdapterShareSameName(adapter_cnt)),
+        match adapter_no {
+            None => Err(Error::AdapterNotFound),
+            Some(no) => Ok(no),
         }
     }
 }
```

**Comment by Q-LiuWei** [comment]
> Do we really need to count how many devices share the same name?
> 
> I'd suggest simplifying the code in this way:
> 
> ```diff
> diff --git a/vhost-device-i2c/src/i2c.rs b/vhost-device-i2c/src/i2c.rs
> index b5abb6a..eaf0b9b 100644
> --- a/vhost-device-i2c/src/i2c.rs
> +++ b/vhost-device-i2c/src/i2c.rs
> @@ -48,8 +48,8 @@ pub(crate) enum Error {
>      ClientAddressInvalid,
>      #[error("Adapter not found")]
>      AdapterNotFound,
> -    #[error("{0} adapters share same name")]
> -    AdapterShareSameName(u32),
> +    #[error("Multiple adapters share the same name")]
> +    AdapterShareSameName,
>      #[error("Std IO Error")]
>      StdIoErr,
>      #[error("Failed while parsing to integer")]
> @@ -350,8 +350,8 @@ impl PhysDevice {
>      }
>  
>      fn find_adapter(name: &str) -> Result<u32> {
> -        let mut adapter_no = 0;
> -        let mut adapter_cnt: u32 = 0;
> +        let mut adapter_no = None;
> +
>          for entry in
>              fs::read_dir(Path::new("/sys/bus/i2c/devices/")).map_err(|_| Error::StdIoErr)?
>          {
> @@ -361,18 +361,17 @@ impl PhysDevice {
>              let adapter_name = fs::read_to_string(path).map_err(|_| Error::StdIoErr)?;
>  
>              if adapter_name.trim() == name {
> +                if adapter_no.is_some() {
> +                    return Err(Error::AdapterShareSameName);
> +                }
> +
>                  let path = entry.path();
>                  let list: Vec<&str> = path.to_str().unwrap().split('-').collect();
> -                adapter_no = list[1].parse::<u32>().map_err(|_| Error::ParseFailure)?;
> -                adapter_cnt += 1;
> +                adapter_no = Some(list[1].parse::<u32>().map_err(|_| Error::ParseFailure)?);
>              }
>          }
>  
> -        match adapter_cnt {
> -            0 => Err(Error::AdapterNotFound),
> -            1 => Ok(adapter_no),
> -            _ => Err(Error::AdapterShareSameName(adapter_cnt)),
> -        }
> +        Ok(adapter_no.ok_or(Error::AdapterNotFound)?)
>      }
>  }
> ```
Thanks for review. @stefano-garzarella 
That's indeed a more elegant way, I like it.
Should I close this PR and you create a new one based on the above?

**Comment by vireshk** [comment]
> Thanks for review. @stefano-garzarella That's indeed a more elegant way, I like it. Should I close this PR and you create a new one based on the above?

You can use the same pull request itself. Just force push your branch.

**Comment by Q-LiuWei** [comment]
@vireshk @stefano-garzarella 
A new version has been pushed.

**Review by vireshk — APPROVED** [review]

**Review by stefano-garzarella — APPROVED** [review]

**Pull request merged**
