### PR TITLE
Set Apache 2.0 OR BSD-3-Clause licenses in all crates

### PR DESCRIPTION
**Pull request by stefano-garzarella**
### Summary of the PR

- Fix SPDX headers of gpio, i2c, and rng crates
- Update crates' readme with the licenses

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Review by vireshk — APPROVED** [review]

**Comment by andreeaflorescu** [comment]
This is the opposite of what we were working on doing with vmm-sys-util (https://github.com/rust-vmm/vmm-sys-util/issues/161) because it makes the crates virtually impossible to use from code that is licensed under GPLv3 and similar licenses. What is the reason behind this change?

Are you sure that none of the code from these crates originated from BSD-3-Clause projects? One example here might be Crosvm as it was used as a starting point for multiple projects.

**Comment by stefano-garzarella** [comment]
> This is the opposite of what we were working on doing with vmm-sys-util ([rust-vmm/vmm-sys-util#161](https://github.com/rust-vmm/vmm-sys-util/issues/161)) because it makes the crates virtually impossible to use from code that is licensed under GPLv3 and similar licenses. What is the reason behind this change?

@vireshk suggested to uniform them.
gpio, i2c, and rng code already had only Apache-2.0 in the SPDX headers.

Since they are executable, I'm not sure if we can have the same issues, but for example for vsock we would like to create a library, so maybe your point is valid and it's better to leave also BSD.

What we should do for gpio, i2c, and rng?

> 
> Are you sure that none of the code from these crates originated from BSD-3-Clause projects? One example here might be Crosvm as it was used as a starting point for multiple projects.

For vsock yes.

**Comment by stefano-garzarella** [comment]
On second thought, I think @andreeaflorescu points is a good point.

So, If everyone agrees, maybe we could do what we did in https://github.com/rust-vmm/vmm-sys-util/issues/161 and just use BSD-3.

For vsock should be okay (@harshanavkis can you confirm?)

For other crates, @stsquad @vireshk @mathieupoirier what do you think?

**Comment by vireshk** [comment]
I am fine with that. I just feel they should all be consistent. That's all.

**Comment by andreeaflorescu** [comment]
> I'm agnostic - whichever open source license makes most sense for the project. I didn't realise Apache 2.0 interacted badly with GPLv3. If the BSD 3 clause is the most liberal then lets do that.

The licensed we proposed for all crates in rust-vmm is Apache 2.0 OR BSD-3-Clause. If this can be used (i.e. if there are no problems with using Apache 2.0 as well), I think this should be the preferred one. This gives the most flexibility in terms of usage.

**Comment by vireshk** [comment]
> The licensed we proposed for all crates in rust-vmm is Apache 2.0 OR BSD-3-Clause. If this can be used (i.e. if there are no problems with using Apache 2.0 as well), I think this should be the preferred one. This gives the most flexibility in terms of usage.

@stefano-garzarella I think you can update your patches with both these licenses now, so we can merge it.

**Comment by stefano-garzarella** [comment]
> > The licensed we proposed for all crates in rust-vmm is Apache 2.0 OR BSD-3-Clause. If this can be used (i.e. if there are no problems with using Apache 2.0 as well), I think this should be the preferred one. This gives the most flexibility in terms of usage.
> 
> @stefano-garzarella I think you can update your patches with both these licenses now, so we can merge it.

Okay, but should we ask to all authors to agree on that?

This is the current situation (without this PR):
- gpio / i2c / rng
  - Cargo.toml: `license = "Apache-2.0 OR BSD-3-Clause"`
  - Source files: `SPDX-License-Identifier: Apache-2.0`
- vsock
  - Cargo.toml: `license = "Apache-2.0 OR BSD-3-Clause"`
  - Source files: `SPDX-License-Identifier: Apache-2.0 or BSD-3-Clause`

So `vsock` should be fine, but in the others we sould change the SPDX tag in the source files.
Since there was discrepancy, could it be a simple fix?

**Comment by andreeaflorescu** [comment]
> So `vsock` should be fine, but in the others we sould change the SPDX tag in the source files. Since there was discrepancy, could it be a simple fix?

For the vmm-sys-util update we asked for one approval from each company that contributed significant code there to simplify the required approvals.

**Comment by vireshk** [comment]
> Okay, but should we ask to all authors to agree on that?
> 
> This is the current situation (without this PR):
> 
> * gpio / i2c / rng
>   
>   * Cargo.toml: `license = "Apache-2.0 OR BSD-3-Clause"`
>   * Source files: `SPDX-License-Identifier: Apache-2.0`

gpio/i2c are from me and rng is from @mathieupoirier. I think he will be fine with the changes, as we kept things similar to how it was done for the the first device merged, i.e. i2c.

> * vsock
>   
>   * Cargo.toml: `license = "Apache-2.0 OR BSD-3-Clause"`
>   * Source files: `SPDX-License-Identifier: Apache-2.0 or BSD-3-Clause`
> 
> So `vsock` should be fine, but in the others we sould change the SPDX tag in the source files.

Right, so all of them are fine I think. At best, I can wait for both Mathieu and Alex to approve the changes before merging.

> Since there was discrepancy, could it be a simple fix?

Yeah, I think you can just all this in the same commit.

**Comment by stefano-garzarella** [comment]
Okay, so an ack from @vireshk and @mathieupoirier should be fine :-)

About BSD-3-clause, I'll add a `LICENSE-BSD-3-Clause` in the root.
Is it okay if I use "The rust-vmm authors" as copyright owner?

**Comment by vireshk** [comment]
> Is it okay if I use "The rust-vmm authors" as copyright owner?

In rust file headers ? They shouldn't be updated I believe, just the licensing part should be enough.

**Comment by stefano-garzarella** [comment]
> > Is it okay if I use "The rust-vmm authors" as copyright owner?
> 
> In rust file headers ? They shouldn't be updated I believe, just the licensing part should be enough.

Nope, I mean in the new LICENSE-BSD-3-Clause file in the root.
It can't be generic, and we should fill the `Copyright <YEAR> <COPYRIGHT HOLDER>`: https://opensource.org/licenses/BSD-3-Clause.

My idea is to add `Copyright 2022 The rust-vmm authors` in the new LICENSE-BSD-3-Clause file in the workspace root, and leave the copyright intact in the various files, that should be fine, right?

Then if a crate doesn't want that copyright, it can redefine a LICENSE-BSD-3-Clause file in the crate itself.

**Comment by vireshk** [comment]
> Nope, I mean in the new LICENSE-BSD-3-Clause file in the root. It can't be generic, and we should fill the `Copyright <YEAR> <COPYRIGHT HOLDER>`: https://opensource.org/licenses/BSD-3-Clause.
> 
> My idea is to add `Copyright 2022 The rust-vmm authors` in the new LICENSE-BSD-3-Clause file in the workspace root, and leave the copyright intact in the various files, that should be fine, right?
> 
> Then if a crate doesn't want that copyright, it can redefine a LICENSE-BSD-3-Clause file in the crate itself.

I am not the right guy to decide on that.

Whatever @andreeaflorescu says is fine :)

**Comment by andreeaflorescu** [comment]
I think generic rust-vmm authors works best because then we don't need to add a lot of copyrights. This was suggested by someone else in the past, I forgot though who. I like the proposal <3

**Comment by stefano-garzarella** [comment]
v2:
- rebased
- added LICENSE-BSD-3-Clause
- fixed SPDX (Apache 2.0 OR BSD-3-Clause) in gpio / i2c / rng
- added License section in crates' readme

**Review by stsquad — APPROVED** [review]

**Review by vireshk — APPROVED** [review]

**Comment by vireshk** [comment]
@mathieupoirier can review and merge this now.

**Comment by vireshk** [comment]
> @mathieupoirier can review and merge this now.

@mathieupoirier can you have a look at this ? We are waiting for you to merge it :)

**Review by mathieupoirier — APPROVED** [review]

**Pull request merged**
