### PR TITLE
ci: Reduce non-rust-vmm crates update frequency

### PR DESCRIPTION
**Pull request by TimePrinciple**
### Summary of the PR

Group `rust-vmm` crates and `non-rust-vmm` crates with security-updates into weekly update, leave the rest dependencies to monthly update in dependabot configuration.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [ ] All added/changed functionality has a corresponding unit/integration
  test.
- [ ] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [ ] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by vireshk** [comment]
@stefano-garzarella any inputs on this ?

**Comment by stefano-garzarella** [comment]
> @stefano-garzarella any inputs on this ?

@vireshk LGTM, we discussed on slack also with @epilys.
@TimePrinciple thanks for this work!

**Review by stefano-garzarella — APPROVED** [review]

**Review by vireshk — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
> 😰 I'll look into how to fix this

What we need to fix?

**Comment by stefano-garzarella** [comment]
> > 😰 I'll look into how to fix this
> 
> What we need to fix?

ah, I see now on main https://github.com/rust-vmm/vhost-device/runs/32976171395

**Comment by TimePrinciple** [comment]
> > > 😰 I'll look into how to fix this
> > 
> > 
> > What we need to fix?
> 
> ah, I see now on main https://github.com/rust-vmm/vhost-device/runs/32976171395

While trying to run dependabot locally, I found a new problem 😂, will fix shortly

image

image

**Comment by stefano-garzarella** [comment]
@TimePrinciple some of them are already fixed by @epilys in #758

**Comment by TimePrinciple** [comment]
> @TimePrinciple some of them are already fixed by @epilys in #758

Thanks for reminding 😉

**Pull request merged**
