### PR TITLE
sound: fix broken tests

### PR DESCRIPTION
**Pull request by epilys**
Tests were not updated with changes in previous commits, so update them.

See https://github.com/rust-vmm/vhost-device/pull/493#issuecomment-1776956302

### CODE REVIEW

**Comment by stefano-garzarella** [comment]
LGTM, I just saw a drop in coverage, maybe related to #487 or #445 :
```
FAILED ../rust-vmm-ci/integration_tests/test_coverage.py::test_coverage - ValueError: Current code coverage (57.35%) deviates by -6.92% from the previous code coverage 50.43%.Current ...
```

@dorindabassey can you take a look about PW tests?

**Review by stefano-garzarella — APPROVED** [review]

**Review by dorindabassey — APPROVED** [review]
LGTM

**Comment by aesteve-rh** [comment]
>  just saw a drop in coverage

Maybe I read it wrong, but isn't it an increased coverage?

**Comment by stefano-garzarella** [comment]
> > just saw a drop in coverage
> 
> Maybe I read it wrong, but isn't it an increased coverage?

Oooo, right! `-6.92%` confused me. We can update `staging/coverage_config_x86_64.json` (maybe in another PR).

**Comment by aesteve-rh** [comment]
> -6.92% confused me

Yeah, the `-` sign is unfortunate. Probably hardcoded in the message… Tbh, it doesn't make much sense to warn/fail if the coverage is increased, no? IMO, the coverage check should set the minimum target.

>  We can update staging/coverage_config_x86_64.json

I can send a quick PR :)

**Comment by stefano-garzarella** [comment]
> > -6.92% confused me
> 
> Yeah, the `-` sign is unfortunate.

yeah!

> Probably hardcoded in the message… Tbh, it doesn't make much sense to warn/fail if the coverage is increased, no? IMO, the coverage check should set the minimum target.

Maybe it's useful to remind us to update the file, otherwise if it grows and we don't update the file, then it decreases, we won't notice the difference.

> 
> > We can update staging/coverage_config_x86_64.json
> 
> I can send a quick PR :)

Thanks!

**Comment by aesteve-rh** [comment]
> Maybe it's useful to remind us to update the file, otherwise if it grows and we don't update the file, then it decreases, we won't notice the difference.

Right, but it may set the coverage bar higher for new crates compared to the ones already integrated. But I understand the reasoning, it is ok. Thanks for explaining :)

**Comment by stefano-garzarella** [comment]
> > Maybe it's useful to remind us to update the file, otherwise if it grows and we don't update the file, then it decreases, we won't notice the difference.
> 
> Right, but it may set the coverage bar higher for new crates compared to the ones already integrated. But I understand the reasoning, it is ok. Thanks for explaining :)

This is true, but we are open to dropping it for good reasons. We use it more as a way to remind ourselves to update it ;-)

**Review by Ablu — APPROVED** [review]

**Review by vireshk — APPROVED** [review]

**Pull request merged**
