### PR TITLE
README: replace master with frontend

### PR DESCRIPTION
**Pull request by stefano-garzarella**
In the vhost-user specs [1] we started using better words for the actors involved, so let's do the same here.

[1] https://qemu-project.gitlab.io/qemu/interop/vhost-user.html

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>

### CODE REVIEW

**Review by vireshk — APPROVED** [review]

**Review by mathieupoirier — COMMENTED** [review]
I think the work "server" is more appropriate here, if only to avoid confusing people with front end drivers found in guest VMs.

**Comment by stefano-garzarella** [comment]
> I think the work "server" is more appropriate here, if only to avoid confusing people with front end drivers found in guest VMs.

IIUC the "server" is the backend (device), and the "client" is the frontend (VMM), no?

Anyway I agree with you (every time I need to open the spec to check the right name), but I think we should follow the spec nomenclature, or change them.

**Comment by mathieupoirier** [comment]
This is definitely a nomenclature issues.  

Earlier you wrote "... but I think we should follow the spec nomenclature, or change them.".

Are you referring to the virtio spec?  Also, can you provide more details on the "or change them" part - I want to make sure I understand your point correctly.

**Comment by stefano-garzarella** [comment]
> This is definitely a nomenclature issues.
> 
> Earlier you wrote "... but I think we should follow the spec nomenclature, or change them.".
> 
> Are you referring to the virtio spec? 

No, I'm referring to vhost-user spec: https://qemu-project.gitlab.io/qemu/interop/vhost-user.html

> Also, can you provide more details on the "or change them" part - I want to make sure I understand your point correctly.

Send a patch to the qemu-devel to update the spec defined in qemu/docs/interop/vhost-user.rst

**Review by mathieupoirier — APPROVED** [review]

**Pull request merged**
