### PR TITLE
buildkite: rename custom-tests.json to staging-tests.json

### PR DESCRIPTION
**Pull request by stefano-garzarella**
Renamed the file to avoid confusion and added a readme to better explain why we want to keep it aligned with
`rust-vmm-ci/.buildkite/test_description.json`

### CODE REVIEW

**Comment by stefano-garzarella** [comment]
I already updated the rule in buildkite UI otherwise the CI here will fail.
For now others PR will fail, but if we decide to don't merge this, I'll change it back.

**Review by epilys — APPROVED** [review]

**Comment by epilys** [comment]
I added a new json file, [.buildkite/cargo-rustfmt.json](https://github.com/rust-vmm/vhost-device/pull/552/files#diff-a195260e1d1b345c1b8b7a5361a9fd9f9e4804c1ec8cf3c48c461ec701fdb0c8),  like we said in the comments in the other PR. Should I put it back to staging-tests.json?

**Comment by stefano-garzarella** [comment]
> I added a new json file, [.buildkite/cargo-rustfmt.json](https://github.com/rust-vmm/vhost-device/pull/552/files#diff-a195260e1d1b345c1b8b7a5361a9fd9f9e4804c1ec8cf3c48c461ec701fdb0c8), like we said in the comments in the other PR. Should I put it back to staging-tests.json?

IMHO is better to have 2 different files, but it is not a strong opinion, I'm fine with both ;-)

**Comment by stefano-garzarella** [comment]
@stsquad @vireshk can you take a look at this PR? In this way, we can unlock the `staging-pipeline` in other PRs.
It is just a rename + README.

**Review by vireshk — APPROVED** [review]

**Pull request merged**
