### PR TITLE
CODEOWNERS: add stefano-garzarella

### PR DESCRIPTION
**Pull request by stefano-garzarella**
I know vhost-user-vsock a bit now, so I'd like to help with reviews and maintaining this workspace.

### CODE REVIEW

**Review by vireshk — APPROVED** [review]

**Review by stsquad — APPROVED** [review]
LGTM! :thumbsup:

**Comment by andreeaflorescu** [comment]
@stefano-garzarella @stsquad @vireshk The process of adding admins is not automated. Once the PR is merged, you need to add people to the repository. More details about how to do this here: https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#becoming-a-repository-maintainer.

For adding maintainers we are asking all existing maintainers to approve the PR before merging. Is there a way to disable automatic merges for these PRs so that we can still follow this policy?

**Comment by vireshk** [comment]
> @stefano-garzarella @stsquad @vireshk The process of adding admins is not automated. Once the PR is merged, you need to add people to the repository. More details about how to do this here: https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#becoming-a-repository-maintainer.

I don't have access to that interface yet for this repository. Should I be added there ? I am not sure :)

> For adding maintainers we are asking all existing maintainers to approve the PR before merging. Is there a way to disable automatic merges for these PRs so that we can still follow this policy?

I already merged this time, but I get it and will make sure everyone approves it next time.

**Comment by andreeaflorescu** [comment]
> > @stefano-garzarella @stsquad @vireshk The process of adding admins is not automated. Once the PR is merged, you need to add people to the repository. More details about how to do this here: https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#becoming-a-repository-maintainer.
> 
> I don't have access to that interface yet for this repository. Should I be added there ? I am not sure :)

That was a mistake. I updated your permissions to admin a couple of hours ago. Can you check again?

**Comment by vireshk** [comment]
> That was a mistake. I updated your permissions to admin a couple of hours ago. Can you check again?

Fixed now, thanks.

**Comment by stefano-garzarella** [comment]
@andreeaflorescu thank you very much for the help!

**Comment by andreeaflorescu** [comment]
> @andreeaflorescu thank you very much for the help!

No problem!

**Pull request merged**
