### PR TITLE
Unwrap crates/ directory

### PR DESCRIPTION
**Pull request by epilys**
### Summary of the PR

After a small discussion on Slack, there seemed to be some positive consensus on altering the directory hierarchy of the crates by moving everything under `crates/` in the root directory.

The reasoning is that, while minor, the extra complexity of the `crates/` hierarchy is not justified by any benefits. Plus, it's idiomatic to have workspace crates on the workspace's directory according to Rust's own documentation: 

<https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html#creating-the-second-package-in-the-workspace>

#### **❗️ Notice ❗️**

The second commit in this PR renames the crate directories themselves to match their crate names as defined in the Cargo manifest files. Since we're making changes here we might as well fix that mismatch as well.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by epilys** [comment]
Reposted because github doesn't allow reopening closed PRs when the branch had been force pushed.

This PR is based on #456

**Comment by stefano-garzarella** [comment]
It looks like GH is not able to understand that we merged #456 ... @epilys can you rebase this PR?

**Comment by stefano-garzarella** [comment]
As I reported in the [discussion for rust-vmm/vhost-device changes](https://github.com/rust-vmm/vhost-device/pull/455#issuecomment-1733990849), my (very weak) preference to keep `crates/` is just to make it straightforward to figure out which crates are in the workspace and divide them from, for example, git submodules present in the root (i.e. `rust-vmm-ci`).

That said it's fine with me if we all agree on this change, and I don't want to stop this for my weak preference.

I would say have a wide consensus before making this change.

@mathieupoirier @stsquad @vireshk  can you approve this PR if you agree on this change (or make a comment if not of course)?

**Review by stefano-garzarella — APPROVED** [review]

**Comment by epilys** [comment]
Rebased against `main`, thanks!

> divide them from, for example, git submodules present in the root (i.e. rust-vmm-ci).

Yes... though my suggestion is still to setup the CI dependencies in the CI runs and pin the rust-vmm-ci ref in a config file. But it's offtopic for this PR

**Review by stefano-garzarella — APPROVED** [review]

**Comment by vireshk** [comment]
> @mathieupoirier @stsquad @vireshk can you approve this PR if you agree on this change (or make a comment if not of course)?

I thought we agreed to merge this once the same changes are pushed for other rust-vmm crates ?

**Comment by stefano-garzarella** [comment]
> > @mathieupoirier @stsquad @vireshk can you approve this PR if you agree on this change (or make a comment if not of course)?
> 
> I thought we agreed to merge this once the same changes are pushed for other rust-vmm crates ?

Sure, I started to see several ACKs on others repo, so I started asking to ACK where I'm the codeowner. Feel free to wait before your ACK, we can wait.

**Comment by epilys** [comment]
Rebased against `main`

**Comment by vireshk** [comment]
> Rebased against `main`

Is this accepted by rust-vmm community already for other repos ?

**Comment by epilys** [comment]
@vireshk there are approvals on most but [only one merge at the moment on vm-superio](https://github.com/rust-vmm/vm-superio/pull/98). I also had added the topic in the etherpad for the next sync meeting.

**Review by vireshk — APPROVED** [review]

**Comment by vireshk** [comment]
@stefano-garzarella I think is ready for merging now. Other crates are updated too in rust-vmm community.

**Comment by stefano-garzarella** [comment]
@vireshk should we wait for an ack (or nack) from all codeowners? @stsquad @mathieupoirier 

I'm fine to merge anyway, but since it is a workspace re-organization, I prefer a big consensus.

**Review by stefano-garzarella — APPROVED** [review]

**Review by stsquad — APPROVED** [review]

**Comment by vireshk** [comment]
Hmm, I think @mathieupoirier is busy with other stuff and since we all agree with this anywa, I will get this merged now..

**Pull request merged**
