### PR TITLE
build: Centralize rust-vmm crates to workspace

### PR DESCRIPTION
**Pull request by TimePrinciple**
### Summary of the PR

- build: Centralize rust-vmm crates to workspace

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [ ] All added/changed functionality has a corresponding unit/integration
  test.
- [ ] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by TimePrinciple** [comment]
It seems that's really a breaking update, I will fix this the first thing tomorrow morning 🧐

**Comment by TimePrinciple** [comment]
Need rust-vmm/vhost#262 to be merged and release :)

**Comment by stefano-garzarella** [comment]
I'm not sure for this workspace is a good idea. I can see the advantage, but maybe it will be hard to keep everything aligned. At the end here we have different binaries, so we can accept that they use different versions.

**Comment by TimePrinciple** [comment]
> I'm not sure for this workspace is a good idea. I can see the advantage, but maybe it will be hard to keep everything aligned. At the end here we have different binaries, so we can accept that they use different versions.

Noted :O, closing this

**Comment by epilys** [comment]
> I'm not sure for this workspace is a good idea. I can see the advantage, but maybe it will be hard to keep everything aligned. At the end here we have different binaries, so we can accept that they use different versions.

+1 These are binaries, not libraries.

**Pull request closed without merging**
