### PR TITLE
Add vhost-user-sound crate

### PR DESCRIPTION
**Pull request by dorindabassey**
### Summary of the PR

This PR adds a new crate, vhost-user-sound, that provides a vhost-user backend daemon for the VIRTIO Sound device as specified in the VIRTIO Spec [v.1.2](https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html)

Supported features are:    
    One input stream, one output stream (hard-coded).
    Playback with Pipewire backend (on host machine).
    Playback with ALSA backend (on host machine).
    Playback with a "null" backend that just consumes audio without actual playback.

What remains to be done:
    Audio capture
    Add more audio backends
    Rust Tests for the sound crate
    Minor Refactoring

Usage / Testing functionality

This PR was tested with QEMU, with a proposed [patchset]( https://patchew.org/QEMU/20231009095937.195728-1-alex.bennee@linaro.org/) that enables generic vhost-user devices in virtualized guests, and vhost-user-snd, vhost-user-snd-pci devices contributed by @stsquad and @epilys 

To Run the vhost-device daemon

`vhost-user-sound --socket=/tmp/vhostsnd.socket --backend pipewire `
or for Alsa
`vhost-user-sound --socket=/tmp/vhostsnd.socket --backend alsa `

Run a guest in QEMU

fetch the Repo https://github.com/virtio-sound/qemu/tree/vhost-user-snd and check out the branch vhost-user-snd (this includes the patchset that enables generic vhost-user devices and vhost-user-snd devices )

    Build QEMU for desired target architecture, e.g. x86_64.

    get or build the kernel enabling the virtio sound module.

    Launch QEMU with
```
    $ /path/to/qemu-system-x86_64  \
       [... snip ...] \
      -chardev socket,id=char0,reconnect=0,path=/tmp/vhostsnd.socket \
      -device vhost-user-snd-pci,chardev=char0 \
      [... snip ...]
```
### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [ ] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by vireshk** [comment]
@dorindabassey Can you please all the build issues ?

**Comment by vireshk** [comment]
@epilys Please convert this to vhost-device-sound (like you have done for others) and create a separate pull rebased over this, we can merge it soon after this is merged. Thanks.

**Comment by stefano-garzarella** [comment]
> @dorindabassey Can you please fix all the build issues ?

It looks like the CI VMs doesn't have alsa libraries. @epilys can you check the errors?

**Comment by stefano-garzarella** [comment]
We will also need to exclude this from coverage since we still need to implement tests (@dorindabassey is working on this).

So, what about if we move this on staging and disable CI for now?

**Comment by vireshk** [comment]
> We will also need to exclude this from coverage since we still need to implement tests (@dorindabassey is working on this).
> 
> So, what about if we move this on staging and disable CI for now?

That may be better actually.

**Comment by stefano-garzarella** [comment]
> > We will also need to exclude this from coverage since we still need to implement tests (@dorindabassey is working on this).
> > So, what about if we move this on staging and disable CI for now?
> 
> That may be better actually.

Okay, so @epilys if you will convert in `vhost-device-sound` in another PR, please can you also move the crate in `staging` including your #466 ?

**Comment by dorindabassey** [comment]
> @dorindabassey Can you please fix all the build issues ?

Added one more commit to fix the build issues, except for the alsa libraries related build issues.

**Comment by vireshk** [comment]
> > @dorindabassey Can you please fix all the build issues ?
> 
> Added one more commit to fix the build issues, except for the alsa libraries related build issues.

These are libc libraries ? You need to add a relevant pull request here then: https://github.com/rust-vmm/rust-vmm-container ..

And before that you need to setup the CI kind of environment (using docker) at your end. The README there explains it.

**Comment by stefano-garzarella** [comment]
> > > @dorindabassey Can you please fix all the build issues ?
> > 
> > 
> > Added one more commit to fix the build issues, except for the alsa libraries related build issues.
> 
> These are libc libraries ? You need to add a relevant pull request here then: https://github.com/rust-vmm/rust-vmm-container ..
> 
> And before that you need to setup the CI kind of environment (using docker) at your end. The README there explains it.

I'll let @epilys check this since he knows better the ALSA requirements.

**Comment by epilys** [comment]
@dorindabassey I believe the `libasound2` and `libasound2-dev` debian packages should be enough for debian/ubuntu images. But we can skip that for now since this is going to `staging` #466

> @stefano-garzarella Okay, so @epilys if you will convert in vhost-device-sound in another PR, please can you also move the crate in staging including your https://github.com/rust-vmm/vhost-device/pull/466 ?

Will do!

**Comment by vireshk** [comment]
> @dorindabassey I believe the `libasound2` and `libasound2-dev` debian packages should be enough for debian/ubuntu images. But we can skip that for now since this is going to `staging` #466

Sure, but start a separate pull request for containers, so that stuff is ready by the time we move sound out of staging.

**Comment by epilys** [comment]
@dorindabassey can you move the crate from `crates/sound` to `staging/vhost-device-sound` since #466 was merged?

**Comment by epilys** [comment]
Closing in favor of #475 which contains this branch but merged with `main`.

**Comment by vireshk** [comment]
> Should be closing this in favor of #475 which contains this branch but merged with `main`.

Will do once that is closed.

**Comment by stefano-garzarella** [comment]
> > @dorindabassey I believe the `libasound2` and `libasound2-dev` debian packages should be enough for debian/ubuntu images. But we can skip that for now since this is going to `staging` #466
> 
> Sure, but start a separate pull request for containers, so that stuff is ready by the time we move sound out of staging.

@epilys we are enabling CI on staging: https://github.com/rust-vmm/vhost-device/pull/479
I think for now it fails because of this problem. CI in staging for now is not blocking, but if you can fix these dependencies that would be great :-)

**Comment by epilys** [comment]
@stefano-garzarella How do I do that? does it run on debian-like container? Is adding apt install[...] enough?

**Comment by vireshk** [comment]
> > > @dorindabassey Can you please fix all the build issues ?
> > 
> > 
> > Added one more commit to fix the build issues, except for the alsa libraries related build issues.
> 
> These are libc libraries ? You need to add a relevant pull request here then: https://github.com/rust-vmm/rust-vmm-container ..
> 
> And before that you need to setup the CI kind of environment (using docker) at your end. The README there explains it.

@epilys here.

**Comment by vireshk** [comment]
@epilys I once did something similar:

https://github.com/rust-vmm/rust-vmm-container/pull/78

**Comment by stefano-garzarella** [comment]
> @stefano-garzarella How do I do that? does it run on debian-like container? Is adding apt install[...] enough?

Yep, it should be debian-like. IIUC we should change this script to install the dependencies: https://github.com/rust-vmm/rust-vmm-container/blob/main/build_container.sh

**Pull request merged**
