### PR TITLE
gpio: use libgpiod from crates.io

### PR DESCRIPTION
**Pull request by Ablu**
This simplifies the packaging and allows using existing tooling to manage further updates.

The lock file was updated with:

    cargo update -p libgpiod --aggressive

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Review by vireshk — APPROVED** [review]

**Comment by vireshk** [comment]
Thanks Erik for working on this. I verified this locally and it all works well :)

**Comment by Ablu** [comment]
@vireshk was the merge of main into this branch intended or did you intend merging the other way around? Shall I rebase this?

**Comment by vireshk** [comment]
> @vireshk was the merge of main into this branch intended or did you intend merging the other way around? Shall I rebase this?

I merged few other pull requests and so updated this branch (which created the merge). Though the policy of merging this git repo is `rebase and merge`, so that new merge commit will not be present eventually in `main` after rebase. You don't need to do anything here.

**Comment by vireshk** [comment]
@stefano-garzarella @stsquad please approve the request whenever you get time :)

**Review by stefano-garzarella — APPROVED** [review]

**Comment by Ablu** [comment]
Thanks!

**Pull request merged**
