### PR TITLE
Add vhost-user-sound crate

### PR DESCRIPTION
**Pull request by epilys**
Merged #473 to main, and moved the crate directory.

### Summary of the PR

This PR adds a new crate, vhost-user-sound, that provides a vhost-user backend daemon for the VIRTIO Sound device as specified in the VIRTIO Spec [v.1.2](https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html)

Supported features are:

- One input stream, one output stream (hard-coded).
- Playback with Pipewire backend (on host machine).
- Playback with ALSA backend (on host machine).
- Playback with a "null" backend that just consumes audio without actual playback.

What remains to be done:

- Audio capture
- Add more audio backends
- Rust Tests for the sound crate
- Minor Refactoring

Usage / Testing functionality

To Run the vhost-device daemon

```shell
vhost-user-sound --socket=/tmp/vhostsnd.socket --backend pipewire
```

or for ALSA

```shell
vhost-user-sound --socket=/tmp/vhostsnd.socket --backend alsa
```

Run a guest in QEMU

This PR was tested with QEMU, with a proposed [patchset](https://patchew.org/QEMU/20231009095937.195728-1-alex.bennee@linaro.org/) that enables generic vhost-user devices in virtualized guests, and vhost-user-snd, vhost-user-snd-pci devices contributed by @stsquad and @epilys

A qemu fork with this patchset is at https://github.com/virtio-sound/qemu/tree/vhost-user-snd, branch `vhost-user-snd`

Build QEMU for desired target architecture, e.g. x86_64.

Get or build the kernel enabling the virtio sound module.

Launch QEMU with:

```
$ /path/to/qemu-system-x86_64  \
   [... snip ...] \
  -chardev socket,id=char0,reconnect=0,path=/tmp/vhostsnd.socket \
  -device vhost-user-snd-pci,chardev=char0 \
  [... snip ...]
```

### Requirements

Before submitting your PR, please make sure you addressed the following requirements:

* [ ]  All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
* [x]  All added/changed functionality has a corresponding unit/integration
  test.
* [x]  All added/changed public-facing functionality has entries in the "Upcoming
  Release" section of CHANGELOG.md (if no such section exists, please create one).
* [x]  Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by dorindabassey** [comment]
LGTM

**Review by vireshk — DISMISSED** [review]
I must admit that I haven't looked into the changes, as discussed earlier separately. We are just merging the changes into the staging tree, which we can then improve and move to main directory after better reviews.

We are merging to staging here to fasten up the process and pick all commit history and credits.

**Comment by vireshk** [comment]
@stsquad @stefano-garzarella please approve this, and then any of us can merge it.

**Comment by stefano-garzarella** [comment]
```
$ git grep vhost-user-sound
staging/Cargo.lock:name = "vhost-user-sound"
staging/vhost-device-sound/Cargo.toml:name = "vhost-user-sound"
staging/vhost-device-sound/README.md:# vhost-user-sound
staging/vhost-device-sound/README.md:generated with help2man target/debug/vhost-user-sound |mandoc
staging/vhost-device-sound/README.md:       vhost-user-sound --socket <SOCKET> --backend <BACKEND>
staging/vhost-device-sound/README.md:host# vhost-user-sound --socket /tmp/snd.sock --backend null
staging/vhost-device-sound/src/lib.rs:/// vhost-user-sound backend server.
staging/vhost-device-sound/src/lib.rs:        String::from("vhost-user-sound"),
```

We can rename them later, but at this point I'd leave `vhost-user-sound` as folder name for consistency.

**Comment by vireshk** [comment]
> We can rename them later, but at this point I'd leave `vhost-user-sound` as folder name for consistency.

Better to fix these instead then ? Since we want folder name to be vhost-device-sound eventually.

**Comment by stefano-garzarella** [comment]
> > We can rename them later, but at this point I'd leave `vhost-user-sound` as folder name for consistency.
> 
> Better to fix these instead then ? Since we want folder name to be vhost-device-sound eventually.

Yep, it's okay for me to fix it now or in a following PR.
But if we want to fix it here, then I would do it in a separate commit (no in the merge commit).

**Comment by vireshk** [comment]
@epilys Have you done all the renames and recent changes in the merge commit ? If yes, then please don't do it that way.

Rebase your changes properly over @dorindabassey 's branch. Such meaningful and significant changes deserver commits of their own. Merge commit should ideally be always empty, unless you have conflicts which can't be fixed otherwise.

**Comment by vireshk** [comment]
> Yep, it's okay for me to fix it now or in a following PR. But if we want to fix it here, then I would do it in a separate commit (no in the merge commit).

+1 for that.

**Review by stsquad — APPROVED** [review]
The are some DCO failures from the early history in the development repo. Because we are keeping the history we shall let that pass along with the one commit style warning.

**Review by stefano-garzarella — APPROVED** [review]

**Review by vireshk — APPROVED** [review]

**Pull request merged**
