### PR TITLE
CODEOWNERS: add epilys, remove mathieupoirier 

### PR DESCRIPTION
**Pull request by epilys**
Add self to CODEOWNERS to contribute with reviewing, merging other PRs and maintaining the vhost-device-sound crate.

Also remove @mathieupoirier, who is unavailable for maintainer duties at
this time.

### CODE REVIEW

**Review by stefano-garzarella — APPROVED** [review]
Maybe it would be better to have an approval and also S-o-b from @mathieupoirier 

A part of that, I'm fine with this change ;-)

**Comment by vireshk** [comment]
> Maybe it would be better to have an approval and also S-o-b from @mathieupoirier

Yeah, he is in agreement and all the existing maintainers need to approve such a request.

**Review by vireshk — APPROVED** [review]

**Comment by vireshk** [comment]
@stsquad I was waiting for Mathieu to approve it too :)

**Comment by epilys** [comment]
Does anything else need to change? I approved Matias' PR and it didn't seem to count towards the 2 minimum required reviews. Also viewing CODEOWNERS on the github UI says:

> Unknown owner on line 2: make sure @epilys exists and has write access to the repository
> 
> … @vireshk @stefano-garzarella @epilys

**Comment by stefano-garzarella** [comment]
> Does anything else need to change? I approved Matias' PR and it didn't seem to count towards the 2 minimum required reviews. Also viewing CODEOWNERS on the github UI says:
> 
> > Unknown owner on line 2: make sure @epilys exists and has write access to the repository
> > … @vireshk @stefano-garzarella @epilys

Right, I just added you among the admins to have read/write access.

**Pull request merged**
