### PR TITLE
RFC: Remove musl target from buildkite tests

### PR DESCRIPTION
**Pull request by epilys**
### Summary of the PR

Musl in CI for staging doesn't work yet. I'd like to ask everyone's opinion on if it's worth keeping or removing to begin with.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by epilys** [comment]
@stefano-garzarella or at least, remove until we add it back and it works. Thoughts?

**Comment by stefano-garzarella** [comment]
> @stefano-garzarella or at least, remove until we add it back and it works. Thoughts?

mmm, I would leave these tests the same as what we then have out of staging, so we always know if we can move a crate or not.

Then these tests are not PR blockers, so what would be the benefit of removing them?

**Comment by stefano-garzarella** [comment]
> Musl in CI for staging doesn't work yet. I'd like to ask everyone's opinion on if it's worth keeping or removing to begin with.

Doesn't it work for any crate in staging or just the sound device?

**Comment by epilys** [comment]
> Then these tests are not PR blockers, so what would be the benefit of removing them?

Ah they are not blockers? I figured if we know they don't work it's not worth keeping them anyway. So let's close this PR.

**Comment by stefano-garzarella** [comment]
> > Then these tests are not PR blockers, so what would be the benefit of removing them?
> 
> Ah they are not blockers? I figured if we know they don't work it's not worth keeping them anyway. So let's close this PR.

No, for now they are not blockers, since `staging` crate are WIP, we decided to not be so stringent.

**Comment by epilys** [comment]
Thanks for clearing it up :) closing

**Pull request closed without merging**
